### ISSUE TITLE
Save news repeatedly

### ISSUE THREAD

**Issue by tenSunFree** [rafsanahmad/Android-MVVM-News-App#1]
Save news repeatedly.
![Screenshot_20211114-223250](https://user-images.githubusercontent.com/23090085/141685716-ca43d87b-1455-45cd-bd98-c2bfdf2e4660.png)

Maybe you can do some judgment processing in DetailsFragment.
<img width="498" alt="2021-11-14_224141" src="https://user-images.githubusercontent.com/23090085/141685948-a604977a-aa9b-45f7-98a8-68028ae06097.png">

**Comment by rafsanahmad** [comment]
Thanks for the suggestion.
Yes, The fab button save the same news article repeatedly,

I have added the codes in DetailsFragment to check if the news article is already favorited or not.

https://github.com/rafsanahmad/Android-MVVM-News-App/commit/959996b55b1f3923615c8674ffdf5f5a1b5aa64e
