### ISSUE TITLE
Will not display OkHttp request response information

### ISSUE THREAD

**Issue by tenSunFree** [rafsanahmad/Android-MVVM-News-App#2]
Because currently BuildConfig corresponds to viewbinding.
<img width="498" alt="2021-11-15_124618" src="https://user-images.githubusercontent.com/23090085/141724607-b6de347f-174a-4e9f-9be7-288cefb52775.png">

Maybe you can change it to correspond to newsapp.
<img width="422" alt="2021-11-15_125444" src="https://user-images.githubusercontent.com/23090085/141724682-2fd5774a-a487-46c3-a277-556d81de42e3.png">

**Comment by rafsanahmad** [comment]
Thanks for the suggestion.
I have added that changes in the latest commit--
https://github.com/rafsanahmad/Android-MVVM-News-App/commit/6c37e509551cb9636216efd8e1922b2613d9ba1d

You can now see the okHttp Response, filter by Tag: "NewsApp"
