### ISSUE TITLE
onScrollListener.isLastPage is always false

### ISSUE THREAD

**Issue by tenSunFree** [rafsanahmad/Android-MVVM-News-App#3]
There is always a blank underneath, because onScrollListener.isLastPage is always false.
![Screenshot_20211119-234113](https://user-images.githubusercontent.com/23090085/142650435-ce8de499-cf00-45ea-bad0-6b8f03006793.png)

Maybe you can try to add some judgment.
<img width="595" alt="2021-11-19_234802" src="https://user-images.githubusercontent.com/23090085/142651270-ab1884ea-b926-46b8-b331-504b792e5fdf.png">

**Comment by rafsanahmad** [comment]
Hi,
Thanks for the suggestion.

I found there was an issue with page count & total page - so bottom padding wasn't hiding.
The fixes are now in the master branch.
